- hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root
  - name: Create CLI file for Master Configurations
      copy:
          dest: "/JBOSS/jboss-master/bin/masterapp.cli"
          content: |
                  # Generated by CICD
                  # You can add/remove commands in below for JBoss CLI
                  # Start embadded controller
                  embed-host-controller --std-out=echo
                  # Create Security Realm and add keystore to config
                  /host=master/core-service=management/security-realm=MYRealm/:add
                  /host=master/core-service=management/security-realm=MYRealm/server-identity= \
                  ssl:add(keystore-path=/JBOSS/Certificate/identity_keystore.jks, \
                  keystore-relative-to=jboss.domain.config.dir, \
                  keystore-password={{jboss_jks_pass}}, alias=jbossserver)
                  # Stop embadded controller
                  stop-embedded-host-controller
                  exit
      become: yes
      become_user: "{{ JBOSS_USER }}"
      register: MasterCLI
  
    - name: Executing jbosscli to Configure Master
      jbosscli:
        jhome: "/JBOSS/jboss-master"
        file: "/JBOSS/jboss-master/bin/masterapp.cli"
      become: yes
      become_user: "{{ JBOSS_USER }}"
      when: MasterCLI is succeeded
